[package]
name = "build-deb-package"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7.4", features = ["fancy"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
