[package]
name = "build-deb-package"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7.5", features = ["fancy"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
anstyle = "1.0"
