FROM debian:unstable

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y wget git debhelper cmake pkg-config jq yq > /dev/null
RUN apt install -y rustc libgtk-4-dev libgtk4-layer-shell-dev libvte-2.91-gtk4-dev libasound2-dev
