version = { specific = "1.0.0" }
dependencies = ["libgtk-4-dev", "libadwaita-1-dev", "git"]
arch = "amd64"
path = ["/root/zig-linux-x86_64-0.13.0"]

[source.git-clone]
url = "https://github.com/ghostty-org/ghostty.git"
branch_or_tag = "v1.0.0"
post_clone_scripts = [
    "wget -q https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -O /root/zig-linux-x86_64-0.13.0.tar.xz",
    "tar xf /root/zig-linux-x86_64-0.13.0.tar.xz -C /root",
    "ls -l /root/zig-linux-x86_64-0.13.0",
]

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "Ghostty is a fast, feature-rich, and cross-platform terminal emulator that uses platform-native UI and GPU acceleration."
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = ["echo skip"]
override_dh_auto_build = ["zig version", "zig build -Doptimize=ReleaseFast"]
override_dh_auto_install = [
    "install -Dm0755 zig-out/bin/ghostty debian/ghostty/usr/bin/ghostty",
]
override_dh_auto_test = ["echo skip"]
