version = { specific = "0.2.6" }
dependencies = ["libpixman-1-dev"]

[source.git-clone]
url = "https://github.com/hyprwm/hyprutils.git"
branch_or_tag = "v0.2.6"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "Hyprland utilities library used across the ecosystem"
arch = "amd64"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
override_dh_auto_configure = ["echo skip"]
override_dh_auto_build = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
    "cmake --build ./build --config Release --target all -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprutils/usr",
]
override_dh_auto_test = ["echo skip"]
