version = { specific = "0.4.2" }
dependencies = ["libpugixml-dev"]

[source.git-clone]
url = "https://github.com/hyprwm/hyprwayland-scanner.git"
branch_or_tag = "v0.4.2"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "A Hyprland implementation of wayland-scanner, in and for C++."
arch = "amd64"
dependencies = []

[debian.rules]
override_dh_auto_configure = ["echo skip"]
override_dh_auto_build = [
    "cmake -DCMAKE_INSTALL_PREFIX=/usr -B build",
    "cmake --build build -j `nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprwayland-scanner/usr",
]
override_dh_auto_test = ["echo skip"]
