version = "0-0-stamp"
dependencies = ["libdbus-1-dev", "libssl-dev", "sassc", "just", "python3"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/iliabylich/layer-shell.git"
branch_or_tag = "master"

[debian]
changelog = true
compat = 10

[debian.control]
description = "A custom layer shell"
dependencies = [
    "${shlibs:Depends}",
    "fonts-inter-variable",
    "python3",
    "python3-setproctitle",
    "python3-gi",
    "libgtk-4-1",
    "libgtk4-layer-shell0",
    "libvte-2.91-gtk4-0",
]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = ["just build-release"]
override_dh_auto_install = ["just install debian/layer-shell"]
