version = "0-0-stamp"
dependencies = [
    "libgtk-4-dev",
    "libgtk4-layer-shell-dev",
    "libvte-2.91-gtk4-dev",
    "libdbus-1-dev",
    "libssl-dev",
    "clang",
    "meson",
    "ninja-build",
]
arch = "amd64"
path = ["/root/.cargo/bin"]

[source.git-clone]
url = "https://github.com/iliabylich/layer-shell.git"
branch_or_tag = "master"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "A custom layer shell"
dependencies = ["${shlibs:Depends}", "fonts-inter-variable"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_configure = [
    "cargo build --release",
    "CC=clang meson setup builddir --buildtype=release --prefix=$$PWD/debian/layer-shell",
]
override_dh_auto_build = ["ninja -C builddir"]
override_dh_auto_install = ["meson install -C builddir"]
