version = "0-0-stamp"
dependencies = [
    "libgtk-4-dev",
    "libgtk4-layer-shell-dev",
    "libvte-2.91-gtk4-dev",
    "libpipewire-0.3-dev",
    "libdbus-1-dev",
    "libssl-dev",
    "libclang1",
    "clang",
]
arch = "amd64"
path = ["/root/.cargo/bin"]

[source.git-clone]
url = "https://github.com/iliabylich/layer-shell.git"
branch_or_tag = "master"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "A custom layer shell"
dependencies = ["${shlibs:Depends}", "fonts-inter-variable"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = [
    "CARGO_TERM_COLOR=always cargo build --release",
    "BUILD_TYPE=release make main",
]
override_dh_auto_install = [
    "install -Dm0644 target/release/liblayer_shell_io.so debian/layer-shell/lib/x86_64-linux-gnu/liblayer_shell_io.so",
    "install -Dm0755 main debian/layer-shell/usr/bin/layer-shell",
]
