version = "0-0-stamp"
dependencies = []
arch = "amd64"

source = "none"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "Meta-package that depends on all packages that I use"
dependencies = [
    # Gnome
    "gnome-session",
    "nautilus",
    "gnome-system-monitor",
    "gnome-icon-theme",
    "gnome-terminal",
    "gdm3",

    # UI apps
    "flatpak",
    "localsend",
    "blanket",
    "mpv",
    "transmission-gtk",
    "amberol",
    "loupe",
    "gedit",
    "baobab",
    "d-spy",
    "file-roller",
    "obfuscate",
    "zenity",

    # Dev tools
    "build-essential",
    "cmake",
    "meson",
    "ragel",
    "valgrind",
    "google-perftools",
    "bison",
    "strace",
    "rustfilt",
    "sqlite3",
    "gh",
    "pkg-config",
    "make",
    "git",
    "llvm",
    "lld",

    # CLI
    "hugo",
    "jq",
    "jsonnet",
    "nmap",
    "yq",
    "pipx",
    "gnupg2",
    "just",
    "git-delta",
    "bat",
    "fastfetch",
    "htop",
    "nano",
    "tree",
    "ffmpeg",
    "libnotify-bin",
    "stow",
    "traceroute",
    "wget",
    "curl",
    "fx",

    # Libs
    "libjemalloc2",
    "libjemalloc-dev",
    "libgtk-4-dev",
    "libgtk4-layer-shell-dev",
    "libadwaita-1-dev",
    "libvte-2.91-gtk4-dev",
    "blueprint-compiler",

    # Debian
    "apt-listbugs",
    "apt-file",
    "netselect-apt",

    # Hyprland
    "hyprland",
    "hyprlock",
    "swaybg",
    "dunst",
    "wl-clipboard",
    "wf-recorder",
    "slurp",
    "grim",
    "cliphist",
    "layer-shell",
    "pavucontrol",
    "syshud",
]

[debian.rules]
"%" = ["dh $@"]
