version = "0-0-stamp"
dependencies = []
arch = "amd64"

source = "none"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "Meta-package that depends on all packages that I use"
dependencies = [
    # Gnome
    "nautilus",
    "gnome-system-monitor",
    "gnome-terminal",
    "tuigreet",
    "greetd",

    # UI apps
    # "flatpak",
    "localsend",
    # "blanket",
    # "mpv",
    # "transmission-gtk",
    # "amberol",
    "loupe",
    # "gedit",
    # "baobab",
    "d-spy",
    # "file-roller",
    # "obfuscate",
    # "zenity",
    "firefox",
    "ghostty",
    "spot",
    "timeshift",

    # Dev tools
    "gcc",
    "build-essential",
    "cmake",
    "meson",
    "ragel",
    "valgrind",
    "google-perftools",
    "bison",
    "strace",
    "rustfilt",
    "sqlite3",
    "gh",
    "pkg-config",
    "make",
    "git",
    "gitk",
    "llvm",
    "clang",
    "lld",
    "clangd",
    "linux-perf",
    "gdb",
    "sassc",

    # CLI
    "hugo",
    "jq",
    "jsonnet",
    "nmap",
    "yq",
    "pipx",
    "gnupg2",
    "just",
    "git-delta",
    "bat",
    "fastfetch",
    "htop",
    "nano",
    "tree",
    "ffmpeg",
    "libnotify-bin",
    "stow",
    "traceroute",
    "wget",
    "curl",
    "fx",
    "starship",
    "du-dust",
    "gaskpass",
    "xremap",
    "pipewire-dbus",
    "apache2-utils",
    "wireplumber",
    "delta",

    # Libs
    "libjemalloc2",
    "libjemalloc-dev",
    "libgtk-4-dev",
    "libgtk4-layer-shell-dev",
    "libadwaita-1-dev",
    "libvte-2.91-gtk4-dev",
    "libpipewire-0.3-dev",
    "libdbus-1-dev",
    "libssl-dev",
    "libgtkmm-4.0-dev",

    # Debian
    "apt-file",
    "make-btrfs-snapshot",
    "xwayland",

    # System
    "autoconf",
    "automake",
    "bash-completion",
    "btrfs-progs",
    "file",
    "less",
    "fakeroot",
    "man-db",
    "manpages",
    "sudo",
    "upower",
    "vim-tiny",
    "grub-common",
    "grub2-common",
    "apparmor",
    "busybox",
    "discover",
    "efibootmgr",
    "iproute2",
    "iputils-ping",
    "isc-dhcp-client",
    "lsb-release",
    "locales",
    "ncurses-term",
    "network-manager",
    "openssh-client",
    "polkitd",
    "usbutils",
    "util-linux-locales",
    "wireless-tools",
    "zlib1g",
    "bind9-dnsutils",
    "bind9-host",

    # Hyprland
    "hyprland",
    "hyprlock",
    "swaybg",
    "dunst",
    "wl-clipboard",
    "wf-recorder",
    "slurp",
    "grim",
    "swappy",
    "cliphist",
    "layer-shell",
    "pavucontrol",
    "swayosd",
    "hyprsunset",
    "hyprland-qtutils",
    "hyprsysteminfo",
    "hyprpolkitagent",
    "hyprland-qt-support",
    "xdg-desktop-portal-hyprland",
    "hyprspace",
]

[debian.rules]
"%" = ["dh $@"]
