version = { specific = "25.05" }
dependencies = [
    "libudev-dev",
    "libseat-dev",
    "libgio-2.0-dev",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libdisplay-info-dev",
    "libpipewire-0.3-dev",
    "libclang-dev",
    "libinput-dev",
    "libxkbcommon-dev",
    "libgbm-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/YaLTeR/niri.git"
branch_or_tag = "v25.05"

[debian]
changelog = true
compat = 10

[debian.control]
description = "A scrollable-tiling Wayland compositor."
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = ["CARGO_TERM_COLOR=always cargo build --release"]
override_dh_auto_install = [
    "install -Dm755 target/release/niri -t debian/niri/usr/bin/",
    "install -Dm755 resources/niri-session -t debian/niri/usr/bin/",
    "install -Dm644 resources/default-config.kdl -t debian/niri/usr/share/doc/niri",
    "install -Dm644 resources/niri.desktop -t debian/niri/usr/share/wayland-sessions/",
    "install -Dm644 resources/niri-portals.conf -t debian/niri/usr/share/xdg-desktop-portal/",
    "install -Dm644 resources/niri.service -t debian/niri/usr/lib/systemd/user/",
    "install -Dm644 resources/niri-shutdown.target -t debian/niri/usr/lib/systemd/user/",
]
