version = "0-0-stamp"
dependencies = [
    "libgtkmm-4.0-dev",
    "libwireplumber-0.5-dev",
    "libevdev-dev",
    "libgtk4-layer-shell-dev",
]

[source.git-clone]
url = "https://github.com/System64fumo/syshud.git"
branch_or_tag = "main"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "Simple heads up display written in gtkmm 4"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
"%" = ["dh $@"]
override_dh_auto_build = ["make all"]
override_dh_auto_install = [
    "make install DESTDIR=\"debian/syshud\" PREFIX=\"/usr\"",
]
override_dh_usrlocal = ["echo skip"]
