version = { specific = "1.0.0-alpha5" }
dependencies = [
    "libegl1-mesa-dev",
    "libfontconfig-dev",
    "libgbm-dev",
    "libinput-dev",
    "libpixman-1-dev",
    "libseat-dev",
    "libsystemd-dev",
    "libudev-dev",
    "libwayland-dev",
    "libxcb1-dev",
    "libxkbcommon-dev",
    "libdisplay-info-dev",
    "cmake",
    "just",
]
arch = "amd64"
env = { VENDOR = "0" }

[source.git-clone]
url = "https://github.com/pop-os/cosmic-comp.git"
branch_or_tag = "epoch-1.0.0-alpha.5"
post_clone_scripts = ["sed -i s/0.1/1.0.0-alpha5/g debian/changelog"]

[debian]
changelog = false
