version = { specific = "1.0.0-alpha5" }
dependencies = ["just", "imagemagick"]
arch = "all"
env = { VENDOR = "0" }
path = ["/root/.cargo/bin"]

[source.git-clone]
url = "https://github.com/pop-os/cosmic-wallpapers.git"
branch_or_tag = "epoch-1.0.0-alpha.5"
post_clone_scripts = [
    "sed -i s/1.0.0/1.0.0-alpha5/g debian/changelog",
    "sed -i s/vendored/release/g debian/rules",
]

[debian]
changelog = false
