version = { specific = "1.0.0-alpha5" }
dependencies = ["just", "libflatpak-dev", "libssl-dev", "libxkbcommon-dev"]
arch = "amd64"
env = { VENDOR = "0" }
path = ["/root/.cargo/bin"]

[source.git-clone]
url = "https://github.com/pop-os/cosmic-store.git"
branch_or_tag = "epoch-1.0.0-alpha.5"
post_clone_scripts = [
    "sed -i s/0.1.0/1.0.0-alpha5/g debian/changelog",
    "sed -i s/vendored/release/g debian/rules",
    "chmod +x debian/rules",
]

[debian]
changelog = false
