version = { specific = "1.0.0-alpha5" }
dependencies = [
    "libclang-dev",
    "libinput-dev",
    "libpam-dev",
    "libwayland-dev",
    "libxkbcommon-dev",
    "just",
]
arch = "amd64"
env = { VENDOR = "0" }
path = ["/root/.cargo/bin"]
additionally_produced_packages = ["cosmic-greeter-daemon"]

[source.git-clone]
url = "https://github.com/pop-os/cosmic-greeter.git"
branch_or_tag = "epoch-1.0.0-alpha.5"
post_clone_scripts = [
    "sed -i s/0.1.0/1.0.0-alpha5/g debian/changelog",
    "sed -i s/vendored/release/g debian/rules",
]

[debian]
changelog = false
