version = { specific = "1.2.4" }
dependencies = ["libxkbcommon-dev", "libegl-dev", "just"]
arch = "amd64"
env = { VENDOR = "0" }
path = ["/root/.cargo/bin"]

[source.git-clone]
url = "https://github.com/pop-os/launcher.git"
branch_or_tag = "1.2.4"
post_clone_scripts = ["sed -i s/vendored/release/g debian/rules"]

[debian]
changelog = false
