version = { specific = "0.6.2" }
dependencies = [
    "/shared/deb-latest/hyprutils.deb",
    "/shared/deb-latest/hyprgraphics.deb",
    "/shared/deb-latest/hyprwayland-scanner.deb",
    "libwayland-dev",
    "wayland-protocols",
    "mesa-common-dev",
    "libgl1-mesa-dev",
    "libhyprlang-dev",
    "libxkbcommon-dev",
    "libjpeg-dev",
    "libwebp-dev",
    "libmagic-dev",
    "libcairo2-dev",
    "librust-pangocairo-dev",
    "libgbm-dev",
    "libpam0g-dev",
    "libsdbus-c++-dev",
]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprlock.git"
branch_or_tag = "v0.6.2"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "Hyprland's GPU-accelerated screen locking utility"
dependencies = ["${shlibs:Depends}"]

[debian.rules]
override_dh_auto_configure = ["echo skip"]
override_dh_auto_build = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -S . -B ./build",
    "cmake --build ./build --config Release --target hyprlock -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprlock/usr",
]
override_dh_auto_test = ["echo skip"]
