version = { specific = "0.6.0-2" }
dependencies = ["/shared/deb-latest/hyprutils.deb"]
arch = "amd64"

[source.git-clone]
url = "https://github.com/hyprwm/hyprlang.git"
branch_or_tag = "v0.6.0"

[debian]
changelog = true
compat = { version = 10 }

[debian.control]
description = "The official implementation library for the hypr config language."
dependencies = ["${shlibs:Depends}"]

[debian.rules]
override_dh_auto_configure = ["echo skip"]
override_dh_auto_build = [
    "cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build",
    "cmake --build ./build --config Release --target hyprlang -j`nproc`",
]
override_dh_auto_install = [
    "cmake --install build --prefix debian/hyprlang/usr",
]
