name: build-base-docker-image

on:
  workflow_dispatch:
    inputs:
      runName:
        description: an ID that is displayed in the name of the run (used for GH CLI scripting)
        required: true

run-name: "${{ github.event.inputs.runName }}"

env:
  IMAGE_NAME: debian-unstable-builder
  IMAGE_ID: ghcr.io/iliabylich/debian-unstable-builder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: docker build . --file docker/Dockerfile.base --tag $IMAGE_NAME --label "runnumber=$GITHUB_RUN_ID"
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: |
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
