name: release

on:
  workflow_dispatch:
    inputs:
      justCommand:
        description: Just command to run
        required: true
      runName:
        description: an ID that is displayed in the name of the run (used for GH CLI scripting)
        required: true

run-name: "${{ github.event.inputs.runName }}"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2

      - run: just ${{ github.event.inputs.justCommand }}

      - run: ls -l

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: ${{ github.event.inputs.justCommand }}
          artifacts: "*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
